public class Check
{
	public enum Name {
		BLINDS_HIDEOUT_TOP,                        // 0
		BLINDS_HIDEOUT_LEFT,                       // 1
		BLINDS_HIDEOUT_RIGHT,                      // 2
		BLINDS_HIDEOUT_FAR_LEFT,                   // 3
		BLINDS_HIDEOUT_FAR_RIGHT,                  // 4
		SECRET_PASSAGE,                            // 5
		WATERFALL_FAIRY_LEFT,                      // 6
		WATERFALL_FAIRY_RIGHT,                     // 7
		KINGS_TOMB,                                // 8
		FLOODGATE_CHEST,                           // 9
		LINKS_HOUSE,                               // 10
		KAKARIKO_TAVERN,                           // 11
		CHICKEN_HOUSE,                             // 12
		AGINAHS_CAVE,                              // 13
		SAHASRAHLAS_HUT_LEFT,                      // 14
		SAHASRAHLAS_HUT_MIDDLE,                    // 15
		SAHASRAHLAS_HUT_RIGHT,                     // 16
		KAKARIKO_WELL_TOP,                         // 17
		KAKARIKO_WELL_LEFT,                        // 18
		KAKARIKO_WELL_MIDDLE,                      // 19
		KAKARIKO_WELL_RIGHT,                       // 20
		KAKARIKO_WELL_BOTTOM,                      // 21
		LOST_WOODS_HIDEOUT,                        // 22
		LUMBERJACK_TREE,                           // 23
		CAVE_45,                                   // 24
		GRAVEYARD_CAVE,                            // 25
		CHECKERBOARD_CAVE,                         // 26
		MINI_MOLDORM_CAVE_FAR_LEFT,                // 27
		MINI_MOLDORM_CAVE_LEFT,                    // 28
		MINI_MOLDORM_CAVE_RIGHT,                   // 29
		MINI_MOLDORM_CAVE_FAR_RIGHT,               // 30
		MINI_MOLDORM_CAVE_GENEROUS_GUY,            // 31
		ICE_ROD_CAVE,                              // 32
		BONK_ROCK_CAVE,                            // 33
		DESERT_PALACE_BIG_CHEST,                   // 34
		DESERT_PALACE_TORCH,                       // 35
		DESERT_PALACE_MAP_CHEST,                   // 36
		DESERT_PALACE_COMPASS_CHEST,               // 37
		DESERT_PALACE_BIG_KEY_CHEST,               // 38
		DESERT_PALACE_DESERT_TILES_1_POT_KEY,      // 39
		DESERT_PALACE_BEAMOS_HALL_POT_KEY,         // 40
		DESERT_PALACE_DESERT_TILES_2_POT_KEY,      // 41
		DESERT_PALACE_BOSS,                        // 42
		EASTERN_PALACE_COMPASS_CHEST,              // 43
		EASTERN_PALACE_BIG_CHEST,                  // 44
		EASTERN_PALACE_DARK_SQUARE_POT_KEY,        // 45
		EASTERN_PALACE_DARK_EYEGORE_KEY_DROP,      // 46
		EASTERN_PALACE_CANNONBALL_CHEST,           // 47
		EASTERN_PALACE_BIG_KEY_CHEST,              // 48
		EASTERN_PALACE_MAP_CHEST,                  // 49
		EASTERN_PALACE_BOSS,                       // 50
		HYRULE_CASTLE_BOOMERANG_CHEST,             // 51
		HYRULE_CASTLE_BOOMERANG_GUARD_KEY_DROP,    // 52
		HYRULE_CASTLE_MAP_CHEST,                   // 53
		HYRULE_CASTLE_MAP_GUARD_KEY_DROP,          // 54
		HYRULE_CASTLE_ZELDAS_CHEST,                // 55
		HYRULE_CASTLE_BIG_KEY_DROP,                // 56
		SEWERS_DARK_CROSS,                         // 57
		SEWERS_KEY_RAT_KEY_DROP,                   // 58
		SEWERS_SECRET_ROOM_LEFT,                   // 59
		SEWERS_SECRET_ROOM_MIDDLE,                 // 60
		SEWERS_SECRET_ROOM_RIGHT,                  // 61
		SANCTUARY,                                 // 62
		CASTLE_TOWER_ROOM_03,                      // 63
		CASTLE_TOWER_DARK_MAZE,                    // 64
		CASTLE_TOWER_DARK_ARCHER_KEY_DROP,         // 65
		CASTLE_TOWER_CIRCLE_OF_POTS_KEY_DROP,      // 66
		SPECTACLE_ROCK_CAVE,                       // 67
		PARADOX_CAVE_LOWER_FAR_LEFT,               // 68
		PARADOX_CAVE_LOWER_LEFT,                   // 69
		PARADOX_CAVE_LOWER_RIGHT,                  // 70
		PARADOX_CAVE_LOWER_FAR_RIGHT,              // 71
		PARADOX_CAVE_LOWER_MIDDLE,                 // 72
		PARADOX_CAVE_UPPER_LEFT,                   // 73
		PARADOX_CAVE_UPPER_RIGHT,                  // 74
		SPIRAL_CAVE,                               // 75
		TOWER_OF_HERA_BASEMENT_CAGE,               // 76
		TOWER_OF_HERA_MAP_CHEST,                   // 77
		TOWER_OF_HERA_BIG_KEY_CHEST,               // 78
		TOWER_OF_HERA_COMPASS_CHEST,               // 79
		TOWER_OF_HERA_BIG_CHEST,                   // 80
		TOWER_OF_HERA_BOSS,                        // 81
		HYPE_CAVE_TOP,                             // 82
		HYPE_CAVE_MIDDLE_RIGHT,                    // 83
		HYPE_CAVE_MIDDLE_LEFT,                     // 84
		HYPE_CAVE_BOTTOM,                          // 85
		HYPE_CAVE_GENEROUS_GUY,                    // 86
		PEG_CAVE,                                  // 87
		PYRAMID_FAIRY_LEFT,                        // 88
		PYRAMID_FAIRY_RIGHT,                       // 89
		BREWERY,                                   // 90
		CSHAPED_HOUSE,                             // 91
		CHEST_GAME,                                // 92
		MIRE_SHED_LEFT,                            // 93
		MIRE_SHED_RIGHT,                           // 94
		SUPERBUNNY_CAVE_TOP,                       // 95
		SUPERBUNNY_CAVE_BOTTOM,                    // 96
		SPIKE_CAVE,                                // 97
		HOOKSHOT_CAVE_TOP_RIGHT,                   // 98
		HOOKSHOT_CAVE_TOP_LEFT,                    // 99
		HOOKSHOT_CAVE_BOTTOM_RIGHT,                // 100
		HOOKSHOT_CAVE_BOTTOM_LEFT,                 // 101
		MIMIC_CAVE,                                // 102
		SWAMP_PALACE_ENTRANCE,                     // 103
		SWAMP_PALACE_MAP_CHEST,                    // 104
		SWAMP_PALACE_POT_ROW_POT_KEY,              // 105
		SWAMP_PALACE_TRENCH_1_POT_KEY,             // 106
		SWAMP_PALACE_HOOKSHOT_POT_KEY,             // 107
		SWAMP_PALACE_BIG_CHEST,                    // 108
		SWAMP_PALACE_COMPASS_CHEST,                // 109
		SWAMP_PALACE_TRENCH_2_POT_KEY,             // 110
		SWAMP_PALACE_BIG_KEY_CHEST,                // 111
		SWAMP_PALACE_WEST_CHEST,                   // 112
		SWAMP_PALACE_FLOODED_ROOM_LEFT,            // 113
		SWAMP_PALACE_FLOODED_ROOM_RIGHT,           // 114
		SWAMP_PALACE_WATERFALL_ROOM,               // 115
		SWAMP_PALACE_WATERWAY_POT_KEY,             // 116
		SWAMP_PALACE_BOSS,                         // 117
		THIEVES_TOWN_BIG_KEY_CHEST,                // 118
		THIEVES_TOWN_MAP_CHEST,                    // 119
		THIEVES_TOWN_COMPASS_CHEST,                // 120
		THIEVES_TOWN_AMBUSH_CHEST,                 // 121
		THIEVES_TOWN_HALLWAY_POT_KEY,              // 122
		THIEVES_TOWN_SPIKE_SWITCH_POT_KEY,         // 123
		THIEVES_TOWN_ATTIC,                        // 124
		THIEVES_TOWN_BIG_CHEST,                    // 125
		THIEVES_TOWN_BLINDS_CELL,                  // 126
		THIEVES_TOWN_BOSS,                         // 127
		SKULL_WOODS_COMPASS_CHEST,                 // 128
		SKULL_WOODS_MAP_CHEST,                     // 129
		SKULL_WOODS_BIG_CHEST,                     // 130
		SKULL_WOODS_POT_PRISON,                    // 131
		SKULL_WOODS_PINBALL_ROOM,                  // 132
		SKULL_WOODS_BIG_KEY_CHEST,                 // 133
		SKULL_WOODS_WEST_LOBBY_POT_KEY,            // 134
		SKULL_WOODS_BRIDGE_ROOM,                   // 135
		SKULL_WOODS_SPIKE_CORNER_KEY_DROP,         // 136
		SKULL_WOODS_BOSS,                          // 137
		ICE_PALACE_JELLY_KEY_DROP,                 // 138
		ICE_PALACE_COMPASS_CHEST,                  // 139
		ICE_PALACE_CONVEYOR_KEY_DROP,              // 140
		ICE_PALACE_FREEZOR_CHEST,                  // 141
		ICE_PALACE_BIG_CHEST,                      // 142
		ICE_PALACE_ICED_T_ROOM,                    // 143
		ICE_PALACE_MANY_POTS_POT_KEY,              // 144
		ICE_PALACE_SPIKE_ROOM,                     // 145
		ICE_PALACE_BIG_KEY_CHEST,                  // 146
		ICE_PALACE_HAMMER_BLOCK_KEY_DROP,          // 147
		ICE_PALACE_MAP_CHEST,                      // 148
		ICE_PALACE_BOSS,                           // 149
		MISERY_MIRE_BIG_CHEST,                     // 150
		MISERY_MIRE_MAP_CHEST,                     // 151
		MISERY_MIRE_MAIN_LOBBY,                    // 152
		MISERY_MIRE_BRIDGE_CHEST,                  // 153
		MISERY_MIRE_SPIKES_POT_KEY,                // 154
		MISERY_MIRE_SPIKE_CHEST,                   // 155
		MISERY_MIRE_FISHBONE_POT_KEY,              // 156
		MISERY_MIRE_CONVEYOR_CRYSTAL_KEY_DROP,     // 157
		MISERY_MIRE_COMPASS_CHEST,                 // 158
		MISERY_MIRE_BIG_KEY_CHEST,                 // 159
		MISERY_MIRE_BOSS,                          // 160
		TURTLE_ROCK_COMPASS_CHEST,                 // 161
		TURTLE_ROCK_ROLLER_ROOM_LEFT,              // 162
		TURTLE_ROCK_ROLLER_ROOM_RIGHT,             // 163
		TURTLE_ROCK_POKEY_1_KEY_DROP,              // 164
		TURTLE_ROCK_CHAIN_CHOMPS,                  // 165
		TURTLE_ROCK_POKEY_2_KEY_DROP,              // 166
		TURTLE_ROCK_BIG_KEY_CHEST,                 // 167
		TURTLE_ROCK_BIG_CHEST,                     // 168
		TURTLE_ROCK_CRYSTAROLLER_ROOM,             // 169
		TURTLE_ROCK_EYE_BRIDGE_BOTTOM_LEFT,        // 170
		TURTLE_ROCK_EYE_BRIDGE_BOTTOM_RIGHT,       // 171
		TURTLE_ROCK_EYE_BRIDGE_TOP_LEFT,           // 172
		TURTLE_ROCK_EYE_BRIDGE_TOP_RIGHT,          // 173
		TURTLE_ROCK_BOSS,                          // 174
		PALACE_OF_DARKNESS_SHOOTER_ROOM,           // 175
		PALACE_OF_DARKNESS_THE_ARENA_BRIDGE,       // 176
		PALACE_OF_DARKNESS_STALFOS_BASEMENT,       // 177
		PALACE_OF_DARKNESS_BIG_KEY_CHEST,          // 178
		PALACE_OF_DARKNESS_THE_ARENA_LEDGE,        // 179
		PALACE_OF_DARKNESS_MAP_CHEST,              // 180
		PALACE_OF_DARKNESS_COMPASS_CHEST,          // 181
		PALACE_OF_DARKNESS_DARK_BASEMENT_LEFT,     // 182
		PALACE_OF_DARKNESS_DARK_BASEMENT_RIGHT,    // 183
		PALACE_OF_DARKNESS_DARK_MAZE_TOP,          // 184
		PALACE_OF_DARKNESS_DARK_MAZE_BOTTOM,       // 185
		PALACE_OF_DARKNESS_BIG_CHEST,              // 186
		PALACE_OF_DARKNESS_HARMLESS_HELLWAY,       // 187
		PALACE_OF_DARKNESS_BOSS,                   // 188
		GANONS_TOWER_CONVEYOR_CROSS_POT_KEY,       // 189
		GANONS_TOWER_BOBS_TORCH,                   // 190
		GANONS_TOWER_HOPE_ROOM_LEFT,               // 191
		GANONS_TOWER_HOPE_ROOM_RIGHT,              // 192
		GANONS_TOWER_TILE_ROOM,                    // 193
		GANONS_TOWER_COMPASS_ROOM_TOP_LEFT,        // 194
		GANONS_TOWER_COMPASS_ROOM_TOP_RIGHT,       // 195
		GANONS_TOWER_COMPASS_ROOM_BOTTOM_LEFT,     // 196
		GANONS_TOWER_COMPASS_ROOM_BOTTOM_RIGHT,    // 197
		GANONS_TOWER_CONVEYOR_STAR_PITS_POT_KEY,   // 198
		GANONS_TOWER_DMS_ROOM_TOP_LEFT,            // 199
		GANONS_TOWER_DMS_ROOM_TOP_RIGHT,           // 200
		GANONS_TOWER_DMS_ROOM_BOTTOM_LEFT,         // 201
		GANONS_TOWER_DMS_ROOM_BOTTOM_RIGHT,        // 202
		GANONS_TOWER_MAP_CHEST,                    // 203
		GANONS_TOWER_DOUBLE_SWITCH_POT_KEY,        // 204
		GANONS_TOWER_FIRESNAKE_ROOM,               // 205
		GANONS_TOWER_RANDOMIZER_ROOM_TOP_LEFT,     // 206
		GANONS_TOWER_RANDOMIZER_ROOM_TOP_RIGHT,    // 207
		GANONS_TOWER_RANDOMIZER_ROOM_BOTTOM_LEFT,  // 208
		GANONS_TOWER_RANDOMIZER_ROOM_BOTTOM_RIGHT, // 209
		GANONS_TOWER_BOBS_CHEST,                   // 210
		GANONS_TOWER_BIG_CHEST,                    // 211
		GANONS_TOWER_BIG_KEY_ROOM_LEFT,            // 212
		GANONS_TOWER_BIG_KEY_ROOM_RIGHT,           // 213
		GANONS_TOWER_BIG_KEY_CHEST,                // 214
		GANONS_TOWER_MINI_HELMASAUR_ROOM_LEFT,     // 215
		GANONS_TOWER_MINI_HELMASAUR_ROOM_RIGHT,    // 216
		GANONS_TOWER_MINI_HELMASAUR_KEY_DROP,      // 217
		GANONS_TOWER_PREMOLDORM_CHEST,             // 218
		GANONS_TOWER_VALIDATION_CHEST,             // 219
		BOTTLE_MERCHANT,                           // 220
		PURPLE_CHEST,                              // 221
		LINKS_UNCLE,                               // 222
		HOBO,                                      // 223
		OLD_MAN,                                   // 224
		KING_ZORA,                                 // 225
		SICK_KID,                                  // 226
		STUMPY,                                    // 227
		SAHASRAHLA,                                // 228
		CATFISH,                                   // 229
		LIBRARY,                                   // 230
		ETHER_TABLET,                              // 231
		BOMBOS_TABLET,                             // 232
		BLACKSMITH,                                // 233
		MUSHROOM,                                  // 234
		POTION_SHOP,                               // 235
		MAGIC_BAT,                                 // 236
		FLUTE_SPOT,                                // 237
		SUNKEN_TREASURE,                           // 238
		ZORAS_LEDGE,                               // 239
		LAKE_HYLIA_ISLAND,                         // 240
		MAZE_RACE,                                 // 241
		DESERT_LEDGE,                              // 242
		MASTER_SWORD_PEDESTAL,                     // 243
		SPECTACLE_ROCK,                            // 244
		PYRAMID,                                   // 245
		DIGGING_GAME,                              // 246
		BUMPER_CAVE_LEDGE,                         // 247
		FLOATING_ISLAND                            // 248
	}
	public const int NUM_CHECKS = 249;

	public readonly ushort address;
	public readonly byte mask;
	public bool isCollected;

	public Check(ushort address, byte mask)
	{
		this.address = address;
		this.mask = mask;
	}
}
